#!/bin/bash
echo "PILIH MENU :"
echo "------------"
PS3="Pilih Menunya : "
JAM=`date +"%d-%m-%Y %T"`

select opt in "push git" "jalankan server" "jam" "keluar"; do

  case $opt in
    "push git")
        git add .
        git commit -m "makuro ${JAM}"
        git push origin main
        echo "---------------"
        echo "     BERES     "
        echo "---------------"
    ;;
    "jalankan server")
        npm run dev
    ;;
    "jam")
        echo ${JAM}
    ;;
    "keluar")
        break
     ;;
    *) 
      echo "Invalid option $REPLY"
      ;;
  esac
done

