#!/bin/bash
menu="
PILIHAN MENU :
1. run server
"
echo "${menu}"
echo -n "Masukkan Pilihannya: "

while :
do
read choice
case $choice in
  1)  echo "mulain menjalankan server"
      npm run dev
  ;;
  *)  echo "hemmm , lihat pilihan di menunya"
esac
  echo -n "Masukkan Pilihannya: "
done